# Build the testserver binary
# Docker command must be invoked from the projec root directory
FROM golang:1.25.5@sha256:20b91eda7a9627c127c0225b0d4e8ec927b476fa4130c6760928b849d769c149 AS builder

ARG TARGETARCH

ENV GOARCH=$TARGETARCH
ENV CGO_ENABLED=1

WORKDIR /src

# Copy the go manifests and source
COPY internal/test/ internal/test/
COPY go.mod go.mod
COPY go.sum go.sum

# Build/link statically with CGO, external static linking
RUN go build -tags -a -ldflags '-linkmode external -extldflags "-static"' -o testserver ./internal/test/integration/components/testserver/testserver.go

# Create final image from minimal + built binary
#TODO: use minimal image
FROM debian:12@sha256:3d957cd5e0693cf44cbb65aa43033fb701443df6b0afa4dcc9293c9bb7a258f9

WORKDIR /
RUN mkdir -p x509
COPY --from=builder /src/internal/test/integration/components/testserver/x509/server_test_cert.pem x509
COPY --from=builder /src/internal/test/integration/components/testserver/x509/server_test_key.pem x509
COPY --from=builder /src/testserver .
USER 0:0

CMD [ "/testserver" ]
