# Development version of the beyla Dockerfile that compiles for coverage
# and allows retrieving coverage files.
# The production-ready minimal image is in the project root's dockerfile.
FROM golang:1.25.5@sha256:20b91eda7a9627c127c0225b0d4e8ec927b476fa4130c6760928b849d769c149 AS builder

ARG TARGETARCH

ENV GOARCH=$TARGETARCH

WORKDIR /

COPY internal/test/integration/components/ebpf-instrument/ebpf_instrument_wrapper.sh /ebpf_instrument_wrapper.sh

WORKDIR /src

# Copy the go manifests and source
COPY .git/ .git/
COPY bpf/ bpf/
COPY cmd/ cmd/
COPY pkg/ pkg/
COPY go.mod go.mod
COPY go.sum go.sum
COPY Makefile Makefile

# Build
RUN make compile-for-coverage

FROM scratch

# Copy the native executable into the containers
COPY --from=builder /src/bin/ebpf-instrument /ebpf-instrument
COPY --from=builder /ebpf_instrument_wrapper.sh /ebpf_instrument_wrapper.sh

WORKDIR /

ENTRYPOINT [ "/ebpf_instrument_wrapper.sh" ]
